"""
BusinessLens AI — AI Cost Optimizer

Routes requests to the cheapest adequate solution:
  1. Cache hit → return cached result (free)
  2. Rules/KPI engine can answer deterministically → no AI call
  3. Only call AI when genuinely needed (schema analysis, NL phrasing)

This ensures AI is used ONLY for irreducibly non-deterministic tasks:
- Schema analysis and field-type inference
- Fuzzy alias matching during mapping suggestion
- Natural language phrasing of insights generated by the rules engine

The cost optimizer NEVER decides what insights to show — only whether
to call AI for phrasing or use a template instead.
"""

from __future__ import annotations

from app.ai.base_provider import AIRequest, AIResponse, BaseAIProvider
from app.cache.base_cache import BaseCacheProvider
from app.core.config import settings
from app.core.logging_config import get_logger

logger = get_logger(__name__)


class AICostOptimizer:
    """
    Gate layer between services and AI provider.

    Usage:
        optimizer = AICostOptimizer(provider=ai_provider, cache=cache)
        response = await optimizer.complete(request, cache_key="ai:schema:conn123:abc")

    Decision tree (when AI_COST_OPTIMIZATION_ENABLED=True):
      1. Check cache → return cached AIResponse if hit
      2. If provider is None (no API key) → raise AIProviderError
      3. Call provider → cache result → return
    """

    def __init__(
        self,
        provider: BaseAIProvider | None,
        cache: BaseCacheProvider | None = None,
    ) -> None:
        self._provider = provider
        self._cache = cache

    async def complete(
        self,
        request: AIRequest,
        cache_key: str | None = None,
        cache_ttl: int | None = None,
    ) -> AIResponse:
        """
        Execute an AI request with optional caching.

        Args:
            request: The AI prompt request.
            cache_key: If provided, check/store result in cache.
            cache_ttl: TTL in seconds for cache storage (defaults to schema analysis TTL).
        """
        # 1. Cache check
        if (
            settings.AI_COST_OPTIMIZATION_ENABLED
            and self._cache is not None
            and cache_key is not None
        ):
            cached = await self._cache.get(cache_key)
            if cached is not None:
                logger.debug("AI cost optimizer: cache hit for key=%s", cache_key[:32])
                # Reconstruct AIResponse from cached dict
                from app.ai.base_provider import AIResponse as _AR
                return _AR(**cached)

        # 2. No provider available
        if self._provider is None:
            from app.core.exceptions import AIProviderError
            raise AIProviderError(
                "none",
                "No AI provider is configured. Set GEMINI_API_KEY or OPENAI_API_KEY "
                "in your environment to enable AI features.",
            )

        # 3. Call provider
        logger.debug(
            "AI cost optimizer: calling provider=%s", self._provider.provider_name
        )
        response = await self._provider.complete(request)

        # 4. Cache result
        if (
            settings.AI_COST_OPTIMIZATION_ENABLED
            and self._cache is not None
            and cache_key is not None
        ):
            ttl = cache_ttl or settings.CACHE_SCHEMA_ANALYSIS_TTL_SECONDS
            await self._cache.set(cache_key, response.__dict__, ttl_seconds=ttl)

        return response

    @property
    def is_available(self) -> bool:
        """True if an AI provider is configured."""
        return self._provider is not None
