/**
 * Dashboard and Charting types (Backend V3 Aligned)
 */

export type WidgetType = 
  | 'LINE'
  | 'BAR'
  | 'PIE'
  | 'AREA'
  | 'HEATMAP'
  | 'SCATTER'
  | 'TABLE'
  | 'KPI'
  | 'BAR_CHART'
  | 'METRIC_CARD';


export type DashboardCategory = 
  | 'EXECUTIVE'
  | 'SALES'
  | 'CUSTOMER'
  | 'INVENTORY'
  | 'FORECAST'
  | 'CUSTOM';

export interface DateRange {
  startDate: string;
  endDate: string;
  preset?: '7D' | '30D' | '90D' | '6M' | '1Y' | 'ALL' | 'CUSTOM';
}

export interface FilterState {
  dateRange: DateRange;
  region?: string;
  category?: string;
  product?: string;
  customerSegment?: string;
  [key: string]: unknown;
}

export interface WidgetConfig {
  id: string;
  title: string;
  subtitle?: string;
  type: WidgetType;
  metric: string; // e.g. "revenue", "profit", "orders"
  dimension?: string; // e.g. "month", "region", "product"
  secondaryMetric?: string;
  filters: FilterState;
  gridPos: {
    x: number;
    y: number;
    w: number;
    h: number;
  };
  formula?: string; // For KPI cards
  businessMeaning?: string;
  dependencies?: string[];
  width?: number;
  height?: number;
  config?: Record<string, unknown>;
  aiExplanation?: string;
  data?: unknown[];
}

export interface DashboardVersion {
  versionId: string;
  dashboardId: string;
  versionNumber: number;
  createdAt: string;
  createdBy: string;
  versionNotes: string;
  widgetsSnapshot: WidgetConfig[];
}

export interface RedisCacheStatus {
  isCached: boolean;
  lastUpdated: string;
  cachedAt: string;
  ttlSeconds: number;
  statusText: 'LIVE' | 'CACHED' | 'REFRESHING';
}

export interface Dashboard {
  id: string;
  title: string;
  category: DashboardCategory;
  description: string;
  createdAt: string;
  updatedAt: string;
  isAutoGenerated: boolean;
  widgets: WidgetConfig[];
  currentVersionNumber: number;
  cacheStatus: RedisCacheStatus;
  widgetCount?: number;
  confidence?: number;
  suggestedWidgets?: string[];
}

export interface InsightCard {
  id: string;
  title: string;
  description: string;
  impact: 'HIGH' | 'MEDIUM' | 'LOW';
  metric: string;
  changePercentage: number;
  trend: 'UP' | 'DOWN' | 'STABLE';
  generatedAt: string;
}

export interface ForecastResult {
  metric: string;
  period: '30_DAYS' | '90_DAYS' | '6_MONTHS' | '1_YEAR';
  dataPoints: {
    date: string;
    actual?: number;
    forecast: number;
    lowerBound: number;
    upperBound: number;
  }[];
  confidenceIntervalPercentage: number; // e.g. 95%
  modelUsed: string;
}

export type RecommendedDashboard = Dashboard;
export type DashboardWidget = WidgetConfig;
